[package]
name = "mcnetwork"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quartz_nbt = "0.2.4"    # NBT library
rand = "0.8.4"

derive_packet = { path = "./derive_packet" }